### ISSUE TITLE
Does QuaRot only support Llama and OPT style LLM?

### ISSUE THREAD

**Issue by NicoNico6** [spcl/QuaRot#27]
Hi, authors, thanks a lot for this nice work. I am also interested in the offline rotation for LLM. I notice that the current roattion is restrcited to Llama and OPT families. Is it possible to combine rotation with other LLMs like Qwen family? Any constrain for the rotation?

**Comment by sashkboos** [comment]
Thanks @NicoNico6 for your issue.

This repo is developed for the paper and that's why we haven't extended the scheme to other models. 

However, Microsoft is developing a [repo](https://github.com/microsoft/TransformerCompression) to support QuaRot and it is really easy to extend to new models. You can find QuaRot in [this](https://github.com/microsoft/TransformerCompression/tree/quarot-main) branch. To extend to a new model, you only need to define an adaptor for your model like [this](https://github.com/microsoft/TransformerCompression/tree/quarot-main/src/quarot/adapters) directory.

Thanks.

**Comment by shuren-z** [comment]
> Hi, authors, thanks a lot for this nice work. I am also interested in the offline rotation for LLM. I notice that the current roattion is restrcited to Llama and OPT families. Is it possible to combine rotation with other LLMs like Qwen family? Any constrain for the rotation?
佬，请问您实现了吗，我最近也在做这方面的工作，目前也遇到了相同的问题。请问您尝试过修改源码或者使用TransformerCompression了吗，效果怎么样呢
