### ISSUE TITLE
mlp_sizes seem wrong in qlinear_benchmark.py

### ISSUE THREAD

**Issue by yyfcc17** [spcl/QuaRot#33]
https://github.com/spcl/QuaRot/blob/main/benchmarks/qlinear_benchmark.py#L53

when benchmark down_proj, the input and output channel should swap their position in *mlp_sizes* config, i.e. [28672, 8192] for llama-70B

after correct this, the latency of hadamard transform becomes noticeable for llama-70B down_proj.

**Comment by sashkboos** [comment]
@yyfcc17 

Thank you so much for your issue. 

The issue is that the CUDA kernel for Hadamard transform (this repo: https://github.com/Dao-AILab/fast-hadamard-transform) applies fast transformation on power-of-two matrices. However, one needs to add another matrix multiplication on top of it (see details [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/hadamard_utils.py#L92-L101)).

However, for a given matrix dimension n (which is not power-of-two), one can solve the performance issue by hardcoding the Hadamard transformations in CUDA. Dao's repo has a nice [code generator](https://github.com/Dao-AILab/fast-hadamard-transform/blob/master/csrc/code_gen.py) for this and you can get reasonable speedups for an specific matrix size.

**Comment by yyfcc17** [comment]
thanks for your answer, but i don't know how the K  in https://github.com/spcl/QuaRot/blob/main/fake_quant/hadamard_utils.py#L7
is choosen.

specifically, for 28672, it will hit **_n  % 28 == 0_** in your  code. do you mean this can be slower than other K setting? so which value should be used to accelerate? 224? (28672 = 224 * 128)

**Comment by yyfcc17** [comment]
i see, thanks for your reply.
