### ISSUE TITLE
A question regarding the rotation matching pairs

### ISSUE THREAD

**Issue by Menace-Dragon** [spcl/QuaRot#36]
SpinQuant is a subsequent work to QuaRot. However, we have noticed that the definitions of the rotation matrix pairing details differ between the two papers. In QuaRot, first, there is an online Hadamard operation (with a dimension of head_dim) before o_proj. Secondly, o_weight is fused with a Hadamard matrix ( H ) of the entire tensor dimension. These highlighted in the red box in the figure below.

![image](https://github.com/user-attachments/assets/74fcbecd-bcf2-40c0-b647-af8ab3187fda)

 In SpinQuant (at below figure), the online Hadamard operation before o_proj is removed. Additionally, o_weight is fused with a Hadamard matrix ( H, now i.e., ![image](https://github.com/user-attachments/assets/3305d1a7-b85a-4c61-92fa-a81b283af70b)) of head_dim dimension. 

![image](https://github.com/user-attachments/assets/dfceb603-a8bd-4568-be65-519ab9c4617d)

Why is this the case? Are the rotation matrix pairings in the two papers equivalent?

**Comment by sashkboos** [comment]
@Menace-Dragon 

Thank you so much for your issue. 

Actually SpinQuant and QuaRot are not using exactly the same rotation tricks (as you mentioned above).

The main point you need to note that the output of v_proj will be divided and multiplied to the attention weights in different heads. So if you multiply a large Hadamard matrix (for example, Hadamard of size 4096 for LLaMa2-7B), you cannot inverse it by applying the inverse of that Hadamard on the o_proj because of head multiplication I mentioned above.

Based on the above fact, what we have done in QuaRot paper is that we apply a Hadamard on each head separately on the output of v_proj (LLaMa2-7B has 32 heads so we apply Hadamards of size 128 on the output of v_proj). Then, before applying the inverse of the transformation in out_proj, we apply another Hadamard between different heads (Hadamard of size 32), so the output will be exactly the same as applying a single Hadamard of 4096 (this property is called Kronecker construction of Hadamard matrices -> See Section 3.1 of the paper). Now, in out_proj we apply the inverse Hadamard of size 4096 and we are done.

There are a few points here:

1. We apply exact Hadamard here as we need to apply online Hadamard of size 32. We need it to be fast,
2. Applying Hadamard on each head will help us to quantize the V-caches as we do them per-head (or group-wise with group-size=128 which is the same as head-dim),
3. Another way of doing the above idea is to remove online Hadamard (of size 32) and apply the inverse over groups (of size 128) columns in the out_proj. We have done this but this results in lower accuracy during the quantization (as we do per-token quantization),
4. SpinQuant does not apply the 32 size Hadamard but instead learns the R_2. This is the main difference between ours and their work (here).

Please let me know if you have any other question

**Comment by HaoKun-Li** [comment]
This question and answer are very nice! I have the same question and solve this question here.

**Comment by HaoKun-Li** [comment]
Actually, I wonder if Figure 6 in the paper has a mistake?
(1) I check the code and found that the RoPE(Q) and RoPE(K) both conduct a Hadamard Transform, while the V does not get a Hadamard Transform.  Is it right?
(2) And it seems that the kv cache after dequanted does not required any other online Hadamard Transform before the attention operation. Is it right?

![Image](https://github.com/user-attachments/assets/a30b7b0f-469f-4f88-9373-ca34e9b6dcaa)

Therefore, maybe the Figure 6 should be like below？

![Image](https://github.com/user-attachments/assets/cd014dce-56b4-420a-b2e8-1df5b8b30c1b)

**Comment by sashkboos** [comment]
Thanks @HaoKun-Li for your issue.

1) Actually, we use the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of the Hadamard transformations. You apply Hadamard in each head on the output of the v_proj and then apply another (online) hadamard between heads. So this means that you will have a tensor with full hadamard transformation (not between heads) and you have to cancel out that using a full hadamard transformation in the out_proj.

2) Not sure that I got your point here. We do quant/dequant in a single function in the above code (this is fake quantization which simulates the quantization operation)

**Comment by HaoKun-Li** [comment]
> Thanks [@HaoKun-Li](https://github.com/HaoKun-Li) for your issue.
> 
> 1. Actually, we use the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of the Hadamard transformations. You apply Hadamard in each head on the output of the v_proj and then apply another (online) hadamard between heads. So this means that you will have a tensor with full hadamard transformation (not between heads) and you have to cancel out that using a full hadamard transformation in the out_proj.
> 2. Not sure that I got your point here. We do quant/dequant in a single function in the above code (this is fake quantization which simulates the quantization operation)

Thanks for you reply sinserely！ What I care is that the hadamard in Figure 6 is confusing. The hadamard after kv cache(in red box) seems redundant. And Ithink that the Value_State do not required addition hadamard(in red box) before kv cache because the hadamard has been absord in W_v

![Image](https://github.com/user-attachments/assets/7bbc6947-966e-43a0-8314-d5091fc52224)

**Comment by sashkboos** [comment]
@HaoKun-Li 

Thanks for your suggestion. Yes, I agree your figure is simpler than what we had in the paper :-)
