### ISSUE TITLE
Do I need to use merge a hadamard matrix into W_v if I only want to do 4 bit KV caching?

### ISSUE THREAD

**Issue by YLGH** [spcl/QuaRot#5]
Hi, 

Just wanted to quickly check my understanding. **Step Stage 1c: Attention Value Projection** is needed for 4 bit matmul right? If I only wanted to do 4 bit KV caching, I don't need to further merge in another hadamard into W_v because I've already done that with Q in the full model rotation step.

Also, could you please kindly point me towards where we do online hadamard transformation for the query + key values? I quickly searched for it but couldn't find it.

Thanks!

**Comment by sashkboos** [comment]
@YLGH 

Thanks. 

You are right. The W_v should be rotated because we want to make sure that the input of the W_out is already rotated. However, you should consider two things:

1. Because we do the computation head-wise (inside attention), we need to rotate each head separately and then apply a partial rotation just before the W_out to have a full rotation.
2. The head-wise rotation of W_v can help us to quantize the values. So you should rotate that if you want to do the KV-Cache quantization. 
3. Using above facts, if you want to do KV-cache quantization only, you need to rotate the W_v for each head (which is already done) and then remove the partial Hadamard transformations (the one that we do online). Then, you need to apply the inverse transform per-head on W_out. This is optional and we haven't tried and the KV-cache results in the paper is also with all above rotations (so we only changed the precisions for KV-caches). But if your goal is KV-cache quantization, you can remove that part of course.

> Also, could you please kindly point me towards where we do online hadamard transformation for the query + key values? I quickly searched for it but couldn't find it.

Sure. Let me explain it in details:

1. To simulate the Value quantization, it is easy as you can quantize the output of the W_v. We do it [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/quant_utils.py#L251). Then, in the `main.py` file, we active such quantization [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/main.py#L92).
2. For Key quantization the situation is a bit tricky because we want to do rotation post-RoPE and we don't want to write the whole attention module from scratch. So we use a wrapper which is called just after RoPE function (see [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/rotation_utils.py#L311)). Then, we  call [this](https://github.com/spcl/QuaRot/blob/main/fake_quant/rotation_utils.py#L288) module. That's it :)

**Comment by YLGH** [comment]
Ah I see thanks for the thorough explanation! 

For step 3, are you referring to 

rotate_ov_proj(layer, num_heads, head_dim) from rotate_model? 

If I only apply rotate_ov_proj to each layer, the model should remain the same right? (The rotation done in V is going to be undone in O)

**Comment by YLGH** [comment]
<img width="602" alt="image" src="https://github.com/spcl/QuaRot/assets/9512279/e791a0de-123f-454e-bf04-9eea7ed91bb9">

Is there a typo for equation (8)? 

does it not need to be (I x H).T applied to the left side of o_proj.weight to keep equivalence?

**Comment by sashkboos** [comment]
>For step 3, are you referring to rotate_ov_proj(layer, num_heads, head_dim) from rotate_model?

yes

> If I only apply rotate_ov_proj to each layer, the model should remain the same right? (The rotation done in V is going to be undone in O)

You should also apply (partial) online hadamard just before out_proj.

>Is there a typo for equation (8)?

No. the rotations should be canceled and that is what you need to do (apply the inverse of the rotation before the actual linear transformation in the o_proj).
